### ISSUE TITLE
Converting to TypeScript

### ISSUE THREAD

**Issue by jacobhumston** [jacobhumston/sxcu.api#9]
I plan on completely converting the package to TypeScript without creating any breaking changes. (Hopefully)

- [x] Organize all endpoints into seperate files. 
- [x] Add new GitHub actions.
- [x] Add new documentation generation for TypeScript specifically.  
- [x] Convert code to TypeScript.
- [x] Change jsdoc definitions to type definitions. 
- [x] Replace repetitive code with private functions.
- [x] Organize everything, update readme to be better formatted.

**Comment by jacobhumston-school** [comment]
*Side note:* Was not planning on it but added CommonJS back!

**Comment by jacobhumston-school** [comment]
Checklist completed: just need to finish some endpoint methods.
